"""empty message

Revision ID: 052b72b2c5ce
Revises: f9314f1a8ed7
Create Date: 2021-10-15 21:29:26.611187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052b72b2c5ce'
down_revision = 'f9314f1a8ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'weight')
    # ### end Alembic commands ###
