"""empty message

Revision ID: 1adec5604d61
Revises: aa9a7e28840f
Create Date: 2021-10-19 21:27:01.825181

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1adec5604d61'
down_revision = 'aa9a7e28840f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'cart_product', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'cart_id')
    # ### end Alembic commands ###
