"""empty message

Revision ID: 463cde5c541e
Revises: 58303c6fd463
Create Date: 2021-10-16 21:19:01.819923

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '463cde5c541e'
down_revision = '58303c6fd463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('psw', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('date_registration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
