"""empty message

Revision ID: 4ed4043c11af
Revises: f561d8eb8f4d
Create Date: 2021-10-10 16:01:16.159951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed4043c11af'
down_revision = 'f561d8eb8f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('photo_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_category', 'photo_url')
    # ### end Alembic commands ###
