"""empty message

Revision ID: 60e797db1de2
Revises: a644fe9095f8
Create Date: 2021-10-15 17:17:47.989791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e797db1de2'
down_revision = 'a644fe9095f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'product_category', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', type_='unique')
    op.drop_column('product_category', 'slug')
    # ### end Alembic commands ###
