"""empty message

Revision ID: 77b53511cf35
Revises: 8e028f11948a
Create Date: 2021-10-19 19:51:08.249618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b53511cf35'
down_revision = '8e028f11948a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_product', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_product', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.drop_column('cart_product', 'product_id')
    # ### end Alembic commands ###
