"""empty message

Revision ID: a78e4b3140d4
Revises: 4ed4043c11af
Create Date: 2021-10-13 21:20:56.240346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78e4b3140d4'
down_revision = '4ed4043c11af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('composition', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'composition')
    # ### end Alembic commands ###
