"""empty message

Revision ID: aa9a7e28840f
Revises: 77b53511cf35
Create Date: 2021-10-19 20:04:48.538667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa9a7e28840f'
down_revision = '77b53511cf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_product_id_fkey', 'cart_product', type_='foreignkey')
    op.drop_column('cart_product', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_product', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_product_product_id_fkey', 'cart_product', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
