"""empty message

Revision ID: ecbafce9836f
Revises: 463cde5c541e
Create Date: 2021-10-19 18:20:48.487015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbafce9836f'
down_revision = '463cde5c541e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'psw',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'psw',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_table('cart')
    # ### end Alembic commands ###
