"""empty message

Revision ID: f561d8eb8f4d
Revises: 01364fac6cb0
Create Date: 2021-10-10 15:59:13.981519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f561d8eb8f4d'
down_revision = '01364fac6cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('photo_url', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_category', 'photo_url')
    # ### end Alembic commands ###
